name: Update README with WakaTime Stats

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch WakaTime stats
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKA_API }}
        run: |
          curl -s "https://wakatime.com/api/v1/users/current/stats/last_7_days?api_key=${{ secrets.WAKA_API }}" > waka_stats.json
          coding_time=$(jq -r '.data.human_readable_total' waka_stats.json)
          echo "Coding time: ${coding_time}"  # Debugging: Output the coding time

      - name: Update README
        run: |
          readme_content=$(cat README.md)
          echo "Current README content:"
          echo "$readme_content"  # Debugging: Output the current README content

          new_content=$(echo "$readme_content" | sed -E "s|(<!--waka-->)[^<]*(<!--endwaka-->)|<!--waka-->Total coding time last week: ${coding_time}<!--endwaka-->|")
          echo "New README content:"
          echo "$new_content"  # Debugging: Output the new README content
          echo "$new_content" > README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update README with WakaTime stats"
          git push
